# ????Profile??
spring:
  profiles:
    active: dev
# ????json???null???????
  jackson:
    default-property-inclusion: non_null

# ?? mybatis ?????SQL???XML????
mybatis:
  mapper-locations: classpath:mapper/*.xml


knife4j:
  enable: true