# ########################### #
# 當前文件中的是【生產環境】的配置 #
# ########################### #

# 連接數據庫配置
spring.datasource.url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username: prod
spring.datasource.password: P@ssw0rd

# 日誌的顯示級別
logging.level.cn.tedu.csmall: warn